# NumPy Practice I
- Basic Overview
- Basic Operation
- Shape Manipulation

In [32]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

In [13]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b = np.array([1.2,3.5,5.1])
b

array([1.2, 3.5, 5.1])

In [16]:
b.dtype

dtype('float64')

In [17]:
# Type Error
a = np.array(1,2,3,4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [19]:
# Correct
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [21]:
b = np.array([[1.5,2,3],(4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [23]:
c = np.array([[1,2],[3,4]], dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [26]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [27]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [34]:
from numpy import pi

In [39]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [36]:
x = np.linspace(0,2*pi,100)

In [37]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [40]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [41]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [47]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [48]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [49]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [50]:
c = a - b
c

array([20, 29, 38, 47])

In [51]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [52]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [53]:
a<35

array([ True,  True, False, False])

In [54]:
A = np.array([[1,1],
              [0,1]])

In [55]:
B = np.array([[2,0],
              [3,4]])

In [56]:
A * B

array([[2, 0],
       [0, 4]])

In [57]:
A @ B

array([[5, 4],
       [3, 4]])

In [58]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [59]:
rg = np.random.default_rng(1)
rg

Generator(PCG64) at 0x2423BEDA900

In [60]:
a = np.ones((2,3), dtype = int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [61]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [62]:
a[2]

8

In [63]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [64]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [65]:
a[::1]

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [66]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [67]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [68]:
def f(x,y):
    return 10 * x + y

In [69]:
b = np.fromfunction(f, (5,4), dtype = int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [70]:
b[2,3]

23

In [71]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [72]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [73]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [74]:
b[-1]

array([40, 41, 42, 43])

In [75]:
c  = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [77]:
c.shape

(2, 2, 3)

In [78]:
c[1, ...]

array([[100, 101, 102],
       [110, 112, 113]])

In [79]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [81]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [82]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [83]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [84]:
mychar = (i for i in '대한민국')
for i in range(3):
    result = next(mychar)
print(result)

민
