# Pandas Basics II

In [1]:
# Pandas Basics
from IPython.display import Image 

from pandas import Series, DataFrame
import pandas as pd
import numpy as np

### 2. Essential functionality
> 핵심 기능 : Series나 DataFrame에 저장된 데이터를 다루는 방법

- Reindexing
- Dropping entries from an axis
- Indexing, selection, and filtering
- Arithmetic and data alignment
- Function application and mapping
- Sorting and ranking

### Reindexing

In [2]:
obj = Series([4.5,7.2,-5.3,3.6], index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj2 = obj.reindex(['a','b','c','d','e'])    # 재정렬!!!!!!!!!!!!!!!!!!!!
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [9]:
obj.reindex(['a','b','c','d','e'], fill_value = 0)    # fill_value : NaN값 대체

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [12]:
# ffill 메소드 : 앞의 값으로 누락된 값을 채워 넣기
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [13]:
obj3.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [14]:
obj3.reindex(range(6), method='ffill')   # 바로 앞의 값으로 누락된값 채워넣음 front fill

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [15]:
obj3.reindex(range(6), method='bfill')   # 바로 뒤의 값으로 누락된값 채워넣음 back fill

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [17]:
frame = DataFrame(np.arange(9).reshape(3,3), index = ['a','c','d'],
                 columns = ['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [18]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [19]:
states = ['Texas','Utah','California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [20]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [21]:
frame.iloc[0:2]

Ohio  Texas  California
a     0      1           2
c     3      4           5

In [22]:
frame.loc['a':'d']

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

### Dropping entries from an axis
> 하나의 로우 또는 칼럼 삭제하기

- 색인 배열 또는 삭제하려는 로우나 칼럼이 제외된 리스트를 이미 가지고 있다면 쉽게 삭제 가능한데...
- 이 방법은 데이터의 모양을 변경하는 작업이 필요하다.
- drop 메소드를 사용하면 선택한 값이 삭제된 새로운 객체를 얻을 수 있다.
- 칼럼 삭제 : drop( [칼럼명], axis=1)
- 로우 삭제 : drop( [로우명], axis=0) or drop( [로우명] ) </font>

In [23]:
obj = Series(np.arange(5.), index = ['a','b','c','d','e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [24]:
obj.drop(['d','c'])  # 실제 data 삭제는 X

a    0.0
b    1.0
e    4.0
dtype: float64

In [25]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [27]:
data = DataFrame(np.arange(16).reshape(4,4),
                index = ['Ohio','Colorado','Utah','NewYort'],
                columns = ['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYort    12   13     14    15

In [28]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah       8    9     10    11
NewYort   12   13     14    15

### [Note] axis=1 denotes that we are referring to a column, not a row

In [29]:
data.drop('two',axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NewYort    12     14    15

In [30]:
data.drop(columns = 'two')

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
NewYort    12     14    15

In [31]:
data.drop(['two','four'], axis = 1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
NewYort    12     14

In [33]:
# data.drop(columns = 'two','four')

SyntaxError: positional argument follows keyword argument (1091141525.py, line 1)

In [38]:
# ?data.drop

### Indexing, selection, and filtering
> 색인하기, 선택하기, 거르기

- Series의 색인(obj[...])은 NumPy 배열의 색인과 유사하게 동작하는데,
- Series의 색인은 정수가 아니어도 된다는 점이 다르다.
- 또한 라벨이름으로 슬라이싱하는 것은 시작점과 끝점을 포함한다는 것이 파이썬과 다른점이다.

In [41]:
obj= Series(np.arange(4.), index = ['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [42]:
obj['b']

1.0

In [43]:
obj[1]

1.0

In [44]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [45]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [47]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [48]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

### 라벨이름으로 슬라이싱 할 경우, 끝점도 포함한다.

In [50]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [51]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [52]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [53]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [54]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [55]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [56]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [57]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [58]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [60]:
data.loc['Colorado', ['two','three']]   # 특정 index / coulumn 값 불러오기!!!!!!!!!!!!!!!!!!!!!!!

two      5
three    6
Name: Colorado, dtype: int32

In [61]:
data.loc['New York','one']

12

In [62]:
data.loc['New York', ['one','two','three']]

one      12
two      13
three    14
Name: New York, dtype: int32

### Arithmetic and data alignment
>산술연산과 데이터 정렬

- pandas 에서 중요한 기능은 색인이 다른 객체 간의 산술연산이다.
- 객체를 더할 때 짝이 맞지 않는 색인이 있다면 결과에 두 색인이 통합된다.

In [63]:
s1 = Series([7.3,-2.5,3.4,1.5], index = ['a','c','d','e'])
s2 = Series([-2.1,3.6,-1.5,4,3.1], index = ['a','c','e','f','g'])

In [64]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [65]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [67]:
s1 + s2   # 둘 중에 하나라도 값 없으면 무조건 NaN 처리

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [68]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [69]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [70]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [71]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values
>산술연산 메소드에 채워 넣을 값 지정하기

In [72]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [73]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [74]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [75]:
df1 + df2   # 둘 중에 값 하나라도 없으면 NaN

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [81]:
df1.add(df2, fill_value=0)   # df2의 NaN값을 0으로 바꾼 후 계산

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [82]:
df1.reindex(columns=df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series
> DataFrame과 Series 간의 연산

In [83]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
arr[0]

array([0., 1., 2., 3.])

In [85]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [87]:
frame = DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
                                        index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [89]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [90]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [91]:
series2 = Series(range(3), index = ['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [92]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [93]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [94]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [97]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function application and mapping
> 함수 적용과 매핑

- pandas 객체에도 NumPy의 유니버설 함수를 적용할 수 있다.
- 유니버설 함수 : 배열의 각 원소에 적용되는 메소드

In [98]:
frame = DataFrame(np.random.randn(4,3), columns = list('bde'),
                 index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -0.119435  0.197207 -0.546746
Ohio   -0.616267 -1.549082 -2.302892
Texas   1.869073 -0.189652 -0.634807
Oregon -1.819044 -0.404145 -1.137769

In [99]:
np.abs(frame)

b         d         e
Utah    0.119435  0.197207  0.546746
Ohio    0.616267  1.549082  2.302892
Texas   1.869073  0.189652  0.634807
Oregon  1.819044  0.404145  1.137769

In [100]:
f = lambda x : x.max() - x.min()

In [103]:
frame.apply(f)   # data frame 에 특정함수 적용 시, .apply()   /   초기값 : axis = 0

b    3.688117
d    1.746289
e    1.756146
dtype: float64

In [104]:
frame.apply(f, axis = 1)

Utah      0.743953
Ohio      1.686625
Texas     2.503880
Oregon    1.414898
dtype: float64

In [106]:
def f(x):
    return Series([x.min(), x.max()], index = ['min','max'])
frame.apply(f)

b         d         e
min -1.819044 -1.549082 -2.302892
max  1.869073  0.197207 -0.546746

In [111]:
# 실수값을 특정 포맷으로 지정!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
format = lambda x : '%.2f' % x
# format = lambda x : '{}.2f'.format(x)    # 이건 안되는듯
frame.applymap(format)

b      d      e
Utah    -0.12   0.20  -0.55
Ohio    -0.62  -1.55  -2.30
Texas    1.87  -0.19  -0.63
Oregon  -1.82  -0.40  -1.14

In [112]:
frame['e'].map(format)

Utah      -0.55
Ohio      -2.30
Texas     -0.63
Oregon    -1.14
Name: e, dtype: object

### Sorting and ranking
> 정렬과 순위

##### index의 정렬

In [113]:
obj = Series(range(4), index = ['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [114]:
frame = DataFrame(np.arange(8).reshape((2,4)), index = ['three','one'],
                 columns = ['d','a','b','c'])
frame.sort_index()    # default값 : axis = 0

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [115]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [117]:
frame.sort_index(axis = 1, ascending = False)  # default : 오름차순 / False 시, 내림차순

d  c  b  a
three  0  3  2  1
one    4  7  6  5

##### value의 정렬

In [118]:
obj = Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [119]:
obj = Series([4,np.nan,7,np.nan,-3,2])   # 문자는 제일 뒤로
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [120]:
frame = DataFrame({'b' : [4,7,-3,2], 'a' : [0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [121]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [122]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

#### ranking

In [123]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [124]:
obj.rank()   # default : average -> 공동 4등이면 (4+5)/2 = 4.5등  ------------------------- 비추

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [129]:
obj.rank(method='min') #-------------------------------------------------공동 4등 -> 이걸로 사용

0    6.0
1    1.0
2    6.0
3    4.0
4    3.0
5    2.0
6    4.0
dtype: float64

In [ ]:
obj.rank(method='max') #--------------------------------------------------------공동 5등 -> 비추

In [130]:
obj.rank(ascending = False, method = 'min')

0    1.0
1    7.0
2    1.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

In [131]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 
                   'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [132]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis indexes with duplicate values
>중복 색인

- pandas의 많은 함수(reindex 같은)에서 색인 값은 유일해야 하지만, 강제 사항은 아니다.

In [133]:
obj = Series(range(5), index = ['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [134]:
obj.index.is_unique

False

In [136]:
obj['a']

a    0
a    1
dtype: int64

In [137]:
obj['c']

4

In [138]:
df = DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])
df

0         1         2
a -0.897337  0.132667 -0.249521
a  0.510788  0.491887  0.173374
b -0.705969  0.502952  0.709013
b -1.030055  1.994441 -0.053265

In [139]:
df.loc['b']

0         1         2
b -0.705969  0.502952  0.709013
b -1.030055  1.994441 -0.053265