In [3]:
# !pip install tensorflow

In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'2.9.1'

>TF01_Hello

In [6]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [7]:
# import tensorflow as tf

hello = tf.constant(" Hello TensorFlow!")
sess = tf.Session()

sess.run(hello)

b' Hello TensorFlow!'

In [8]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [9]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

>TF02_Variable

In [10]:
#first_session_only_tensorflow.py

x = tf.constant(100, name='x')
y = tf.Variable(x*2, name='y')

model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    print("constant x : {x} \nVariable y : {y}".format(
        x = sess.run(x), 
        y = sess.run(y)
    ))

constant x : 100 
Variable y : 200


In [11]:
# 변수 a, b는 동적으로 지정
a = tf.placeholder("int32")
b = tf.placeholder("int32")

# multiply 함수는 입력된 정수 a와 b의 곱셈을 반환한다.
y = tf.multiply(a,b)

sess = tf.Session()

print("tf.multiply({a},{b}) : {y}".format(
    a = 20, b = 30,
    y = sess.run(y , feed_dict={a: 20, b: 30})
))

tf.multiply(20,30) : 600


In [12]:
a = tf.constant(10, name="a")
b = tf.constant(20, name="b")
y = tf.Variable(a**2 + b**2, name="y")

model = tf.global_variables_initializer()

with tf.Session() as sess:
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter("./graph/board", sess.graph)
    sess.run(model)
    print(" constant a = {a} \n constant b = {b} \n Variable y = {y}".format(
        a = sess.run(a), 
        b = sess.run(b),
        y = sess.run(y)
    )) 

 constant a = 10 
 constant b = 20 
 Variable y = 500


In [13]:
!tensorboard --logdir=graph/board --port=9999

^C


In [15]:
import numpy as np

tensor_1d = np.array([1.2, 3.4, 5.6, 7.8])
tensor_2d = np.arange(16).reshape((4,4))

In [16]:
tf_tensor = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)

with tf.Session() as sess:
    print(sess.run(tf_tensor))
    print(sess.run(tf_tensor[0]))
    print(sess.run(tf_tensor[-1]))

[1.2 3.4 5.6 7.8]
1.2
7.8


In [17]:
tf_tensor_1d = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)
tf_tensor_2d = tf.convert_to_tensor(tensor_2d, dtype=tf.float64)
sess = tf.Session()

In [18]:
sess.run(tf_tensor_1d)

array([1.2, 3.4, 5.6, 7.8])

In [19]:
sess.run(tf_tensor_1d[0])

1.2

In [20]:
sess.run(tf_tensor_1d[2:])

array([5.6, 7.8])

In [21]:
sess.run(tf_tensor_2d)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [22]:
sess.run(tf_tensor_2d[3][3])

15.0

In [23]:
sess.run(tf_tensor_2d[1:3,1:3])

array([[ 5.,  6.],
       [ 9., 10.]])