### Sect1. TensorFlow 개요
> Getting Started With TensorFlow

### Check TF version

In [1]:
import numpy as np
import tensorflow.compat.v1 as tf

# tf.disable_v2_behavior()
tf.compat.v1.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


### Hello TensorFlow!

In [2]:
# Create a constant op
# This op is added as a node to the default graph
hello = tf.constant("Hello, TensorFlow!")

# seart a TF session
sess = tf.Session()

In [4]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
# run the op and get result
sess.run(hello)

b'Hello, TensorFlow!'

In [6]:
result = sess.run(hello)
type(result)

bytes

#### [TIP] b 'String'

- 'b' indicates Bytes literals.
- 참조 : What does the 'b' character do in front of a string literal?

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
type(sess)

tensorflow.python.client.session.Session

### Computational Graph

In [9]:
# node1 = tf.constant(3.0, tf.float32)
node1 = tf.constant(3.0)
node2 = tf.constant(4.0)            # also tf.float32 implicitly
node3 = tf.add(node1, node2)
# node3 = node1 + node2

In [10]:
print("node1 :", node1)
print("node2 :", node2)
print("node3 :", node3)

node1 : Tensor("Const_1:0", shape=(), dtype=float32)
node2 : Tensor("Const_2:0", shape=(), dtype=float32)
node3 : Tensor("Add:0", shape=(), dtype=float32)


In [11]:
sess = tf.Session()
print("sess.run(node1, node2)\t: ", sess.run([node1, node2]))
print("sess.run(adder_node)  \t: ", sess.run(node3))

sess.run(node1, node2)	:  [3.0, 4.0]
sess.run(adder_node)  	:  7.0


In [12]:
type(node3)

tensorflow.python.framework.ops.Tensor

In [13]:
type(sess.run(node3))

numpy.float32

### Placeholder

In [14]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

# + provides a shortcut for tf.add(a, b)
adder_node = a + b  

In [15]:
sess.run(adder_node, feed_dict={a: 3, b: 4.5})

7.5

In [16]:
sess.run(adder_node, feed_dict={a: [1,3], b: [2, 4]})

array([3., 7.], dtype=float32)

In [17]:
add_and_triple = adder_node * 3.

In [18]:
sess.run(add_and_triple, feed_dict={a: 3, b:4.5})

22.5

In [19]:
# import tensorflow as tf
# import numpy as np

# 변수 a, b는 동적으로 지정
# a = tf.placeholder("float32")
# b = tf.placeholder("float32")
a = tf.placeholder("int32")
b = tf.placeholder("int32")

# multiply 함수는 입력된 정수 a와 b의 곱셈을 반환한다.
# y = tf.mul(a,b)
y = tf.multiply(a,b)

sess = tf.Session()

print("tf.mul({a},{b}) : {y}".format(
    a = 20, b = 30,
    y = sess.run(y , feed_dict={a: 20, b: 30})
))

tf.mul(20,30) : 600


### Constant & Variable

In [20]:
#first_session_only_tensorflow.py
# import tensorflow as tf
# import numpy as np

x = tf.constant(100, name='x')
y = tf.Variable(x*2, name='y')

# model = tf.global_variables_initializer()
model = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(model)
    print("Check the variable : \n- constant x : {x} \n- Variable y : {y}".format(
        x = sess.run(x), 
        y = sess.run(y)
    ))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
Check the variable : 
- constant x : 100 
- Variable y : 200


### Everything is Tensor
- Tensor Ranks, Shapes, and Types
- n차원 Array == n차원 Tensor

In [21]:
rank0 = 3
rank0

3

In [22]:
rank1 = [1. ,2., 3.]
rank1

[1.0, 2.0, 3.0]

In [23]:
rank2 = [[1., 2., 3.], 
         [4., 5., 6.]]
rank2

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [24]:
rank3 = [
            [
                [1., 2., 3.]
            ], 
            [
                [7., 8., 9.]
            ]
] 
rank3

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

### 텐서플로우 연산

In [25]:
tensor_1d = np.array([1.2, 3.4, 5.6, 7.8])
tensor_1d

array([1.2, 3.4, 5.6, 7.8])

In [26]:
tensor_2d = np.arange(16).reshape((4,4))
tensor_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
sess = tf.Session()
tf_tensor_1d = tf.convert_to_tensor(tensor_1d,dtype=tf.float64)
tf_tensor_2d = tf.convert_to_tensor(tensor_2d,dtype=tf.float64)

In [28]:
sess.run(tf_tensor_1d)

array([1.2, 3.4, 5.6, 7.8])

In [29]:
sess.run(tf_tensor_1d[0])

1.2

In [30]:
sess.run(tf_tensor_1d[2:])

array([5.6, 7.8])

In [31]:
sess.run(tf_tensor_2d)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [32]:
#sess.run(tf_tensor_2d[3][3])
sess.run(tf_tensor_2d[3, 3])

15.0

In [33]:
sess.run(tf_tensor_2d[1:3, 1:3])

array([[ 5.,  6.],
       [ 9., 10.]])

In [34]:
import tensorflow as tf
import numpy as np

# 3x3 행렬
matrix1 = np.array([(1, 1, 1), (1, 1, 1), (1, 1, 1)])
matrix2 = np.array([(2, 2, 2), (2, 2, 2), (2, 2, 2)])

# constant, 텐서 자료 구조로 변환
# matrix1 = tf.constant(matrix1)
# matrix2 = tf.constant(matrix2)
matrix1 = tf.constant(matrix1, dtype='int32')
matrix2 = tf.constant(matrix2, dtype='int32')

# 행렬곱과 행렬합 계산
matrix_mul = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1, matrix2)

# 행렬의 행렬식(determinant)
matrix3 = np.array([(2, 7, 2), (1, 4, 2), (9, 0, 2)], dtype='float32')
print('\n* matrix3 = \n{}'.format(matrix3))

# matrix_dtm = tf.matrix_determinant(matrix3)
matrix_dtm = tf.linalg.det(matrix3)
print('\n* matrix_dtm = {} '.format(matrix_dtm))

# 세션을 열고 그래프 연산
# with tf.Session() as sess:
#     result1 = sess.run(matrix_mul)
#     result2 = sess.run(matrix_sum)
#     result3 = sess.run(matrix_dtm)
    
#     # tensorboard for graph
#     writer = tf.summary.FileWriter("./graph/sect01", sess.graph)


* matrix3 = 
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]

* matrix_dtm = Tensor("MatrixDeterminant:0", shape=(), dtype=float32) 


In [35]:
# matrix_dtm = tf.matrix_determinant(matrix3)
matrix_dtm = tf.linalg.det(matrix3)
matrix_dtm

<tf.Tensor 'MatrixDeterminant_1:0' shape=() dtype=float32>

In [36]:
# 세션을 열고 그래프 연산
# sess = tf.compat.v1.Session()
with tf.compat.v1.Session() as sess:
    result1 = sess.run(matrix_mul)
    result2 = sess.run(matrix_sum)
    result3 = sess.run(matrix_dtm)
    
    # tensorboard for graph
    # writer = tf.summary.FileWriter("./graph/sect01", sess.graph)
    writer = tf.compat.v1.summary.FileWriter("./graph/board", sess.graph)

# 연산 결과 출력
print('\n* matrix_mul = \n{}'.format(result1))
print('\n* matrix_sum = \n{}'.format(result2))
print('\n* matrix_dtm = {}'.format(result3))


* matrix_mul = 
[[6 6 6]
 [6 6 6]
 [6 6 6]]

* matrix_sum = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]

* matrix_dtm = 55.99999237060547
