In [1]:
# 데이터 처리
import numpy as np
import pandas as pd
# 머신러닝 알고리즘 및 평가
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
import sklearn.preprocessing as preprocessing
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve
# 시각화
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# 데이터 불러오기
dat = pd.read_csv('./data/classification_parkinsons.csv')

# 데이터 확인해보기 상위 10개를 통해서
'''
print(___________)
'''


'\nprint(___________)\n'

In [5]:
# 데이터의 형태 확인해보기
'''
dat.____
'''

(195, 24)

In [1]:
# 의미없는 변수 제거: name


# name 변수 제거하기
dat_processing = dat._____(['name'], axis=1, inplace=False)

print(dat_processing.columns)

'''


NameError: name 'dat' is not defined

In [7]:
# Normalization
dat_processing_norm = preprocessing.minmax_scale(dat_processing)
dat_processed = pd.DataFrame(dat_processing_norm)
dat_processed.columns = dat_processing.columns

In [8]:
dat_processed.shape


(195, 23)

In [9]:
# 상수항 추가 : sm.add_constant()
'''
dat_processed = sm._______(dat_processed, has_constant='add')
print(dat_processed.head(20))

'''

    const  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0     1.0     0.184308      0.112592      0.054815        0.195680   
1     1.0     0.198327      0.094930      0.278323        0.254130   
2     1.0     0.165039      0.059128      0.265288        0.280178   
3     1.0     0.165004      0.072927      0.264200        0.263342   
4     1.0     0.161150      0.080909      0.260107        0.354511   
5     1.0     0.187568      0.059232      0.278139        0.254130   
6     1.0     0.185909      0.071647      0.284086        0.052414   
7     1.0     0.110606      0.023873      0.223606        0.038755   
8     1.0     0.043063      0.061082      0.151289        0.121665   
9     1.0     0.039139      0.036658      0.148249        0.115629   
10    1.0     0.000000      0.020607      0.107062        0.107052   
11    1.0     0.020789      0.028019      0.119843        0.118170   
12    1.0     0.282892      0.117826      0.378827        0.039708   
13    1.0     0.2959

In [4]:
# 전체 데이터 변수 확인
print(dat_processed.columns)

NameError: name 'dat_processed' is not defined

In [11]:
# Target 변수: 'status'를 제외한 데이터 학습데이터 구성하기
dat_processed.columns.difference(["status"])

Index(['D2', 'DFA', 'HNR', 'Jitter:DDP', 'MDVP:APQ', 'MDVP:Fhi(Hz)',
       'MDVP:Flo(Hz)', 'MDVP:Fo(Hz)', 'MDVP:Jitter(%)', 'MDVP:Jitter(Abs)',
       'MDVP:PPQ', 'MDVP:RAP', 'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'NHR',
       'PPE', 'RPDE', 'Shimmer:APQ3', 'Shimmer:APQ5', 'Shimmer:DDA', 'const',
       'spread1', 'spread2'],
      dtype='object')

In [13]:
feature_columns = list(dat_processed.columns.difference(["status"]))
feature_columns

['D2',
 'DFA',
 'HNR',
 'Jitter:DDP',
 'MDVP:APQ',
 'MDVP:Fhi(Hz)',
 'MDVP:Flo(Hz)',
 'MDVP:Fo(Hz)',
 'MDVP:Jitter(%)',
 'MDVP:Jitter(Abs)',
 'MDVP:PPQ',
 'MDVP:RAP',
 'MDVP:Shimmer',
 'MDVP:Shimmer(dB)',
 'NHR',
 'PPE',
 'RPDE',
 'Shimmer:APQ3',
 'Shimmer:APQ5',
 'Shimmer:DDA',
 'const',
 'spread1',
 'spread2']

In [14]:
X = dat_processed[feature_columns]
y = dat_processed['status'] # 질환여부: 1 or 0

In [16]:
# train_test_split 함수를 이용하여 학습데이터와 검증데이터로 9:1로 나누어 데이터를 구분해보자.
'''
train_x, test_x, train_y, test_y = '__________'(X, y, stratify=y, test_size='___', random_state=2017010500)
print(train_x.shape, test_x.shape, train_y.shape, test_y.shape)
'''

(175, 23) (20, 23) (175,) (20,)


In [17]:
print(dat_processed.dtypes)


const               float64
MDVP:Fo(Hz)         float64
MDVP:Fhi(Hz)        float64
MDVP:Flo(Hz)        float64
MDVP:Jitter(%)      float64
MDVP:Jitter(Abs)    float64
MDVP:RAP            float64
MDVP:PPQ            float64
Jitter:DDP          float64
MDVP:Shimmer        float64
MDVP:Shimmer(dB)    float64
Shimmer:APQ3        float64
Shimmer:APQ5        float64
MDVP:APQ            float64
Shimmer:DDA         float64
NHR                 float64
HNR                 float64
status              float64
RPDE                float64
DFA                 float64
spread1             float64
spread2             float64
D2                  float64
PPE                 float64
dtype: object

In [19]:
print(train_y.head(10))
print(train_x.head(10))


(178    1.0
 89     1.0
 126    1.0
 8      1.0
 193    0.0
 174    0.0
 186    0.0
 92     1.0
 37     1.0
 47     0.0
 75     1.0
 135    1.0
 73     1.0
 177    1.0
 127    1.0
 147    1.0
 84     1.0
 81     1.0
 59     1.0
 42     0.0
 88     1.0
 52     0.0
 32     0.0
 111    1.0
 189    0.0
 106    1.0
 160    1.0
 114    1.0
 18     1.0
 134    1.0
       ... 
 10     1.0
 97     1.0
 93     1.0
 60     0.0
 159    1.0
 118    1.0
 132    1.0
 120    1.0
 149    1.0
 98     1.0
 112    1.0
 121    1.0
 194    0.0
 16     1.0
 17     1.0
 161    1.0
 155    1.0
 46     0.0
 49     0.0
 168    0.0
 53     0.0
 71     1.0
 35     0.0
 55     1.0
 133    1.0
 96     1.0
 166    0.0
 158    1.0
 151    1.0
 0      1.0
 Name: status, Length: 175, dtype: float64,
            D2       DFA       HNR  Jitter:DDP  MDVP:APQ  MDVP:Fhi(Hz)  \
 178  0.368467  0.749886  0.649069    0.040456  0.045180      0.114749   
 89   1.000000  0.682231  0.139194    0.155402  0.209511      0.252682   
 1

In [20]:
# 모델 구축 및 학습
# statsmodels의 logit함수를 이용하여 모델을 적합해보자
'''
model = '_________'(train_y, train_x)
'''

In [5]:
# 모델을 실제로 적합해보자
'''
results = model.____(method='bfgs')
'''

NameError: name 'model' is not defined

In [94]:
# performance measure
print("model AIC: ","{:.5f}".format(results.aic))
print("model BIC: ","{:.5f}".format(results.bic))
results.summary()

model AIC:  28.00189
model BIC:  66.67233


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      Y   No. Observations:                  117
Model:                          Logit   Df Residuals:                      103
Method:                           MLE   Df Model:                           13
Date:                Sun, 13 Jan 2019   Pseudo R-squ.:                   1.000
Time:                        22:25:41   Log-Likelihood:            -0.00094735
converged:                       True   LL-Null:                       -80.580
                                        LLR p-value:                 1.148e-27
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
V1          -131.3890        nan        nan        nan         nan         nan
V10          -77.3007        nan        nan        nan         nan         nan
V11           87.8636        nan        nan        nan         nan         nan
V12           -9.8595        nan        nan        nan         nan         nan
V13         -172.4788        nan        nan        nan         nan         nan
V2           -33.9721        nan        nan        nan         nan         nan
V3          -117.7264        nan        nan        nan         nan         nan
V4            96.9049        nan        nan        nan         nan         nan
V5           -40.2736        nan        nan        nan         nan         nan
V6             7.6310        nan        nan        nan         nan         nan
V7           -35.6265        nan        nan        nan         nan         nan
V8            38.1382        nan        nan        nan         nan         nan
V9            36.9072        nan        nan        nan         nan         nan
const        161.2942        nan        nan        nan         nan         nan
==============================================================================

Possibly complete quasi-separation: A fraction 0.98 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [97]:
# 실제 Train 학습의 예측값을 출력해보자.
'''
train_y_pred = results.'______'(train_x)
print(train_y_pred.head(10))
'''

23     9.988729e-44
129    1.000000e+00
82     1.000000e+00
92     1.000000e+00
118    1.000000e+00
68     1.000000e+00
96     1.000000e+00
123    1.000000e+00
0      2.666831e-39
10     2.598862e-23
dtype: float64


In [98]:
# 실제 Test데이터의 예측값을 출력해보자.
'''
test_y_pred = results.'_____'(test_x)
print(test_y_pred.head(20))
'''

83     1.000000e+00
84     1.000000e+00
31     2.497188e-84
111    1.000000e+00
43     1.173782e-49
105    1.000000e+00
57     3.905277e-49
108    1.000000e+00
71     1.000000e+00
26     1.524508e-62
7      1.302212e-13
85     1.000000e+00
45     1.699351e-49
dtype: float64


In [99]:
# Cut-off 정의
def cut_off(y,threshold):
    Y = y.copy() # copy함수를 사용하여 이전의 y값이 변화지 않게 함
    Y[Y>threshold]=1
    Y[Y<=threshold]=0
    return(Y.astype(int))

In [100]:
train_y_pred_prob = results.predict(train_x)
train_y_pred = cut_off(train_y_pred_prob,0.5)
print( train_y_pred.head(10) )

23     0
129    1
82     1
92     1
118    1
68     1
96     1
123    1
0      0
10     0
dtype: int32


In [101]:
test_y_pred_prob = results.predict(test_x)
test_y_pred = cut_off(test_y_pred_prob,0.5)
print( test_y_pred.head(20) )

83     1
84     1
31     0
111    1
43     0
105    1
57     0
108    1
71     1
26     0
7      0
85     1
45     0
dtype: int32


In [102]:
test_y_pred_prob = results.predict(test_x)
test_y_pred = cut_off(test_y_pred_prob,0.5)
print( test_y_pred.head(10) )

83     1
84     1
31     0
111    1
43     0
105    1
57     0
108    1
71     1
26     0
dtype: int32


In [103]:
# confusion matrix: Training set
cm_train = confusion_matrix(train_y,train_y_pred)
print( cm_train )

[[53  0]
 [ 0 64]]


In [104]:
# confusion matrix: Test set
cm_test = confusion_matrix(test_y,test_y_pred)
print( cm_test)

[[6 0]
 [0 7]]


In [105]:
# performance evaluation
def perf_eval(cm):
    # True positive rate: TPR
    TPR = cm[1, 1] / sum(cm[1]) # recall
    # True negative rate: TNR
    TNR = cm[0, 0] / sum(cm[0])
    # Simple Accuracy
    ACC = (cm[0, 0] + cm[1, 1]) / sum(cm.reshape(-1,))
    # Balanced Correction Rate
    BCR = np.sqrt(TPR * TNR)
    # F1-measure
    Precision = cm[1,1] /sum(cm[:,1])
    F1 = 2*TPR*Precision/(TPR+Precision)
    return ([TPR, TNR, ACC, BCR, F1])

In [106]:

print('Test performance of Logistic Regression')
print('TPR:',perf_eval(cm_test)[0])
print('TNR:',perf_eval(cm_test)[1])
print('ACC:',perf_eval(cm_test)[2])
print('BCR:',perf_eval(cm_test)[3])
print('F1:',perf_eval(cm_test)[4])

Test performance of Logistic Regression
TPR: 1.0
TNR: 1.0
ACC: 1.0
BCR: 1.0
F1: 1.0


In [107]:
# 임계값에 따른 비교
threshold = np.arange(0, 1, 0.1)
threshold

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [108]:
table = pd.DataFrame(columns=['TPR','TNR','ACC','BCR','F1'])
print(table)

Empty DataFrame
Columns: [TPR, TNR, ACC, BCR, F1]
Index: []


In [110]:
for i in threshold:
    test_y_pred_tmp = cut_off(test_y_pred_prob,i)
    cfmat = confusion_matrix(test_y, test_y_pred_tmp)
    table.loc[i] = perf_eval(cfmat)

In [111]:
table.index.name='threshold'
table.columns.name='performance'
print(table)

performance  TPR  TNR       ACC  BCR   F1
threshold                                
0.0          1.0  0.0  0.538462  0.0  0.7
0.1          1.0  1.0  1.000000  1.0  1.0
0.2          1.0  1.0  1.000000  1.0  1.0
0.3          1.0  1.0  1.000000  1.0  1.0
0.4          1.0  1.0  1.000000  1.0  1.0
0.5          1.0  1.0  1.000000  1.0  1.0
0.6          1.0  1.0  1.000000  1.0  1.0
0.7          1.0  1.0  1.000000  1.0  1.0
0.8          1.0  1.0  1.000000  1.0  1.0
0.9          1.0  1.0  1.000000  1.0  1.0
