# Pandas Basics I
> pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language

>pandas 개요

- 고수준의 자료구조 와 파이썬을 통한 통한 빠르고 쉬운 데이터 분석도구 를 포함하는 라이브러리
- NumPy 기반에서 개발 되었다.
- Series와 DataFrame은 로컬 네임스페이스로 import 하는 것이 훨씬 편하다.

## 1. Introduction to pandas data structures
>pandas 자료 구조 소개

- Series 와 DataFrame 이 두가지 자료구조에 대해 익숙해지도록 하자.
- 이 두가지 자료구조가 모든 문제를 해결할 수는 없지만, 대부분의 애플리케이션에서 사용하기 쉽고 탄탄한 기반을 제공한다.

>Series
- Series는 일련의 객체를 담을 수 있는 1차원 배열 같은 자료 구조
- Index라고 하는 배열의 데이터에 연관된 이름을 가지고 있다.

In [1]:
# Pandas Basics
from IPython.display import Image 

from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [2]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [7]:
obj2 = Series([4,7,-5,3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']   # 변수값 불러오기

-5

In [10]:
obj2['d'] = 6   # 변수값 지정(엎어쓰기)
obj2[['c','a','d']]   # 해당 변수값만 가져오기

c    3
a   -5
d    6
dtype: int64

In [11]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [12]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2   # 특정 index 보유 여부 확인

True

In [17]:
'e' in obj2

False

In [19]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
states = ['California','Ohio','Oregon','Texas']
obj4 = Series(sdata,index = states)   # Series(value, index)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [24]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
obj3 + obj4   # union all

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'population'    # date set 이름 지정
obj4.index.name = 'state'   # index명 지정
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

### DataFrame
- 표 같은 스프레드시트 형식의 자료구조로 여러개의 칼럼을 가진다.
- 각 칼럼은 서로 다른 종류의 값(숫자, 문자, 불리언 등)을 담을 수 있다.
- 로우와 칼럼에 대한 Index가 있는데, Index의 모양이 같은 Series 객체를 담고 있는 파이썬 사전으로 생각하자.
- Dataframe은 데이터를 내부적으로 2차원 형식으로 저장
- 고차원의 표 형식 데이터를 계층적 색인(Hierarchical Indexing)을 통해 쉽게 표현할 수 있다.

### -----------------------------실무 - 이해하자!!!--------------------------------- ###

In [34]:
# DataFrame 객체 생성1
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002],
        'pop'  : [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [35]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [36]:
# 순서 지정
DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [37]:
# Data Frame 객체 생성2
frame2 = DataFrame(data, columns = ['year','state','pop','debt'],
                         index = ['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [38]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [39]:
# 칼럼 가져오기 1)
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [41]:
# 칼럼 가져오기 2)
frame2.year       # 나는 이게 편한듯 하다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [43]:
# 로우는 위치나 ix 메소드 통해 접근
# frame2.ix['three'] # 안됨

In [44]:
# 행 가져오기 1) frame2.loc[]
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [45]:
# 행 가져오기 2) frame2.iloc[]   # index location
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [65]:
# -------------------------------------------------------------------------------------------
# 특정값 입력하기(변경)
frame2.debt = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [66]:
frame2.debt = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [67]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [127]:
frame2['eastern'] = frame2.state == 'Ohio'   # 불린형 coulmn 추가
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [128]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [129]:
# 칼럼 삭제!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
del frame2['eastern']
# del frame2.eastern    # 이건 왜 안되는듯 / drop으로 해서 해볼 것!
# frame2.drop(columns = 'eastern', inplace = True)   # 요거로는 가능, inplace = True로 해서 가능
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [130]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

### 기본 구조
index column1 column2 column3 column4 column5 ...
  1
  2
  3
  4
  5
 ...

In [78]:
# 행 삭제!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
frame2.drop('two', axis=0)   # view 형태에서만 삭제되고 실제 data에서는 삭제 안됨!!!

year   state  pop  debt
one    2000    Ohio  1.5   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [79]:
# 행 삭제!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
frame2.drop(index='one')   # view 형태에서만 삭제되고 실제 data에서는 삭제 안됨!!!

year   state  pop  debt
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [80]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [83]:
frame2.drop('year', axis = 1)

state  pop  debt
one      Ohio  1.5   NaN
two      Ohio  1.7  -1.2
three    Ohio  3.6   NaN
four   Nevada  2.4  -1.5
five   Nevada  2.9  -1.7

In [85]:
frame2.drop(columns = 'state')   # 위에 방식꺼보단 이걸로 하자!!!

year  pop  debt
one    2000  1.5   NaN
two    2001  1.7  -1.2
three  2002  3.6   NaN
four   2001  2.4  -1.5
five   2002  2.9  -1.7

In [ ]:
# 실제 행 삭제 방법!!!!!!!
frame2.drop(columns = 'state', inplace = True)   # inplace = True!!!   /   주의해서 쓸 것!!!

>[Tip] DataFrame의 색인을 이용해서 생성된 칼럼은 내부 데이터에 대한 뷰(View)이며 복사가 이루어지지 않는다.

- 이렇게 얻은 Series 객체에 대한 변경은 실제 DataFrame에 반영된다.
- 복사본이 필요할 때는 Series의 copy 메소드를 이용

In [91]:
pop = {'Nevada' : {2001 : 2.4, 2002 : 2.9},
        'Ohio'  : {2000 : 1.5, 2001 : 1.7, 2002 : 3.6}}
frame3 = DataFrame(pop)

In [92]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [93]:
# 행렬 변환
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [94]:
DataFrame(pop, index = ['2001','2002','2003'])

Nevada  Ohio
2001     NaN   NaN
2002     NaN   NaN
2003     NaN   NaN

In [95]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [96]:
pdata = {'Ohio'  : frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [97]:
frame3.values   # value값 가져오기

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [98]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [99]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

### Index objects
>pandas의 색인 객체

- 표 형식의 데이터에서 각 로우와 칼럼에 대한 이름과 다른 메타데이터(축의 이름 등)을 저장하는 객체
- Series나 DataFrame 객체를 생성할 때 사용되는 배열이나 혹은 다른 순차적인 이름은 내부적으로 색인으로 변환
- 색인 객체는 변경할 수 없다. 그래서~~~ 자료구조사이에서 안전하게 공유될 수 있다.^^

In [132]:
obj = Series(range(3), index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [133]:
index[1:]

Index(['b', 'c'], dtype='object')

In [135]:
# 색인객체 변경 시 TypeError 발생!
# index[1] = 'd'

In [137]:
index = pd.Index(np.arange(3))
obj2 = Series([1.5, -2.5, 0], index=index)
obj2.index is index

True

In [138]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [139]:
'Ohio' in frame3.columns

True

In [140]:
2003 in frame3.index

False